# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20160831_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
