# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160903_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='need_notifi',
            field=models.BooleanField(default=False),
        ),
    ]
